### ISSUE TITLE
Setting transaction.animation changes how the whole ContentView loads

### ISSUE THREAD

**Issue by flashyhuckle** [marwaniaaj/CustomAlertSwiftUI#1]
Hi, I discovered some potential side effect in your code.

When you set:

`transaction.animation = .linear(duration: 0.1)`

in both View extension methods, it actually affects whole View the customAlerts are a part of. If you change duration to for example 1.0, you can see it slowly in action - the View animates its appearance.
Also I don't think it affects how the alert itself is presented.

**Comment by marwaniaaj** [comment]
Thank you for pointing that out..
But the `transaction.animation = .linear(duration: 0.1)` in both extension function is for the `fullScreenCover` and not for the `CustomAlert`, it's replacing the default animation for the `fullScreenCover` with a custom animation.
If you comment the `.transaction { }` block, you will see the default animation for `fullScreenCover`.

**Comment by flashyhuckle** [comment]
I understand what you are saying, but it affects how the whole ContentView is appearing - it all "comes" from the left, instead of just appearing. Set duration to 1.0 and observe it in "slow motion". 
Also the if you comment the line `transaction.animation = .linear(duration: 0.1)`it does not affect the way fullScreenCover animates.

**Comment by marwaniaaj** [comment]
It is coming from the left because of this line `.transition(.slide)` on the `VStack` in `CustomAlertView`, it's explained in the tutorial.

And yes `transaction.animation = .linear(duration: 0.1)` does not affect the way `fullScreenCover` animates after disabling the default animation, it's where you should put any custom animation if you would like to present `fullScreenCover` differently, if you are satisfied with the current animation then feel free to remove the line in your app.

**Comment by flashyhuckle** [comment]
I don't think we understand each other. I know the CustomAlertView should slide from the left and it is how you set it up. Im saying that `transaction.animation` affects ContentView - the whole view under the alert, and it shouldn't.

This is what happens when you set `.linear(duration: 1.0)` :
https://github.com/marwaniaaj/CustomAlertSwiftUI/assets/66034170/95f73913-6605-4167-a2e8-83e534648564

**Comment by marwaniaaj** [comment]
Ok.. got your point now!
This is new, it didn't happen before because I always debug with "Slow Animations" option.
Let me debug more and check what's the cause.

**Comment by flashyhuckle** [comment]
Yeah, I tried it with Slow Animations, and with `.linear(duration: 0.1)` it was actually harder to see than with normal speed. I don't see the line affecting `fullScreenCover` or `CustomAlertView` in any way, so maybe the easiest fix would be to just remove it?

**Comment by marwaniaaj** [comment]
Yes of course it is the easiest way to simply remove it, but it's better to look for work around, and leave this line for any developer who wants to change the animation in their own app.

**Comment by marwaniaaj** [comment]
@flashyhuckle thank you for contributing to solve this issue.
